verison: '3'

services:
  main:
    container_name: messanger
    restart: always
    build: .
    ports:
      - 3005:3005
    command:
      - npm run start
    env_file:
      - .env
    network_mode: host
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pg_db
      POSTGRES_PASSWORD: appdbpassword
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
