version: '3'

networks:
  network1:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - network1
    ports:
      - 5554:5432

  main:
    container_name: messanger
    restart: always
    build: .
    command:
      npm start
    network_mode: host
    ports:
      - 3006:3006
    depends_on:
      - postgres
