export const routes = {
  API: '/api',
  USER: '/user',
  CHAT: '/chat',
  MESSAGES: '/messages',
  GET_CHATS: '/get-chats',
  SIGN_UP: '/sign-up',
  SIGN_IN: '/sign-in',
  ACCEPT_INVITATION: '/accept-invitation',
  CONFIRM_EMAIL: '/confirm-email',
  FORGOT_PASSWORD: '/forgot-password',
  CHANGE_PASSWORD: '/change-password',
  ERROR: '/error',
  ADD_USER_TO_CHAT: '/add-user-to-chat',
  CREATE_CHAT: '/create-chat',
  CREATE_MESSAGE: '/create-message',
  GET_MESSAGES: '/get-messages',
};
